version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./backend:/usr/src/app
    command: node server.js

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    environment:
      - API_URL=http://192.168.1.135:3000
    depends_on:
      - backend