services:
  app:
    image: nodeimage
    container_name: nodeserver
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    command: node server.js