version: '3'
services:
  backend:
    build:
      context: .  # Usa el directorio actual (donde está el docker-compose.yml)
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./backend:/usr/src/app  # Ajusta si es necesario
    command: node server.js

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend