version: '3'
services:
  backend:
    build:
      context: .  # Asumiendo que Dockerfile está en la raíz
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./backend:/usr/src/app  # Ajusta si es necesario
    command: node server.js